# Generated by Django 4.1.2 on 2022-10-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
