# Generated by Django 4.1.2 on 2022-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_events_event_rename_plans_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
